### PR TITLE
added migration

### PR DESCRIPTION
**Pull request by daanzap**
This migration is missing and creates a problem with deployment

### CODE REVIEW

**Comment by maccesch** [comment]
thanks man!

**Comment by daanzap** [comment]
No problem!
Thanks for merging.

**Comment by daanzap** [comment]
I just saw that in choices in form_layout now contains the form from our
settings.

**Comment by maccesch** [comment]
Sorry, I don't understand what you mean

**Comment by daanzap** [comment]
https://github.com/maccesch/cmsplugin-contact/blob/master/cmsplugin_contact/migrations_django/0002_auto_20160810_1130.py#L17

this automatically copies the value from the settings.py
so now it is set to our custom template.

this is the line causing the trouble:

choices=settings.CMSPLUGIN_CONTACT_FORMS

on the line:
https://github.com/maccesch/cmsplugin-contact/blob/master/cmsplugin_contact/models.py#L31
I'll check if it's possible to dynamicly add choices without triggering a
migration

  Grt,
    Daan

**Pull request merged**
